# Generated by Django 3.2.8 on 2021-11-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200, null=True)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=200, null=True)),
                ('publisher', models.TextField(null=True)),
                ('platform', models.TextField(null=True)),
                ('modes', models.TextField(null=True)),
            ],
        ),
    ]
