# Generated by Django 3.2.8 on 2021-11-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.games'),
        ),
        migrations.AlterField(
            model_name='details',
            name='modes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='platform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='publisher',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
