# Generated by Django 3.2.8 on 2021-11-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211110_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=200, null=True)),
                ('processor', models.CharField(max_length=200, null=True)),
                ('memory', models.CharField(max_length=200, null=True)),
                ('graphics', models.CharField(max_length=200, null=True)),
                ('storage', models.CharField(max_length=200, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.games')),
            ],
        ),
    ]
