# Generated by Django 3.2.8 on 2021-11-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='images',
            field=models.ImageField(null=True, upload_to='myimage', verbose_name=''),
        ),
    ]
