# Generated by Django 3.2.8 on 2021-11-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_details_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='images',
        ),
    ]
