# Generated by Django 3.2.8 on 2021-11-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_games_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='photo',
            new_name='image',
        ),
    ]
