# Generated by Django 3.2.8 on 2021-11-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211119_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.checkout'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.register'),
        ),
    ]
