# Generated by Django 3.2.8 on 2021-11-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211126_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bill_id',
            new_name='bill',
        ),
    ]
