# Generated by Django 3.2.8 on 2022-01-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220110_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='qty',
        ),
    ]
