# Generated by Django 3.2.8 on 2022-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_games_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(null=True)),
                ('email_from', models.CharField(max_length=50)),
                ('recipient_list', models.CharField(max_length=50)),
            ],
        ),
    ]
