# Generated by Django 3.2.8 on 2022-02-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_email_register_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='user_email',
            new_name='email',
        ),
    ]
