# Generated by Django 3.2.8 on 2022-02-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220214_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='games',
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.games'),
        ),
    ]
