# Generated by Django 3.2.8 on 2022-02-15 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20220215_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.games'),
        ),
    ]
