# Generated by Django 3.2.8 on 2022-02-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
