# Generated by Django 3.2.8 on 2022-02-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_customer_order_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='sub_total',
            new_name='price',
        ),
    ]
