# Generated by Django 3.2.8 on 2022-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20220225_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
