# Generated by Django 3.2.8 on 2022-03-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20220302_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
