# Generated by Django 3.2.8 on 2022-03-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_order_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='myimage', verbose_name='')),
                ('price', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('Game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.games')),
            ],
        ),
    ]
