# Generated by Django 3.2.8 on 2022-03-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Game',
            new_name='game',
        ),
    ]
