# Generated by Django 3.2.8 on 2022-03-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_rename_order_order_item_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
