# Generated by Django 3.2.8 on 2022-03-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20220327_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(null=True, upload_to='myimage', verbose_name=''),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='games',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
