# Generated by Django 3.2.8 on 2022-03-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_wishlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
    ]
