# Generated by Django 3.2.8 on 2022-03-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20220331_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.games'),
        ),
    ]
