# Generated by Django 3.2.8 on 2022-04-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_register'),
        ('home', '0061_alter_wishlist_games'),
    ]

    operations = [
    ]
